version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install -v
      - run:
          name: ls
          command: ls -ltra
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Test
          command: ./node_modules/jest/bin/jest.js -- --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
  lint:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Lint
          command: ./node_modules/eslint/bin/eslint --format junit -o reports/junit/js-lint-results.xml
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
workflows:
  version: 2
  test_lint:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
