version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Test
          command: yarn test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
